-- Khởi tạo toàn bộ schema cho chat-core-service (Oracle)
-- Bao gồm 7 bảng: CHAT_CONVERSATION, CHAT_MESSAGE, CHAT_CONTEXT,
--                  CHAT_ATTACHMENT, CHAT_OUTBOX, CHAT_ASSIGNMENT_HISTORY, CHAT_AUDIT_LOG

-- 1. CHAT_CONVERSATION: Quản lý phiên hội thoại
CREATE TABLE CHAT_CONVERSATION (
    CONVERSATION_ID     VARCHAR2(36)    NOT NULL,
    USER_ID             VARCHAR2(64)    NOT NULL,
    MERCHANT_ID         VARCHAR2(64),
    TOPIC_CODE          VARCHAR2(64),
    STATUS              VARCHAR2(32)    DEFAULT 'NEW'        NOT NULL,
    ASSIGNED_AGENT      VARCHAR2(64),
    SLA_DEADLINE        TIMESTAMP,
    FIRST_RESPONSE_AT   TIMESTAMP,
    CLOSED_AT           TIMESTAMP,
    LAST_MESSAGE_ID     VARCHAR2(36),
    VERSION             NUMBER(19)      DEFAULT 0            NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHAT_CONVERSATION PRIMARY KEY (CONVERSATION_ID)
);

CREATE INDEX IDX_CONV_STATUS_TOPIC ON CHAT_CONVERSATION (STATUS, TOPIC_CODE);
CREATE INDEX IDX_CONV_USER         ON CHAT_CONVERSATION (USER_ID);
CREATE INDEX IDX_CONV_AGENT        ON CHAT_CONVERSATION (ASSIGNED_AGENT);

-- 2. CHAT_MESSAGE: Quản lý từng tin nhắn
CREATE TABLE CHAT_MESSAGE (
    MESSAGE_ID        VARCHAR2(36)    NOT NULL,
    CONVERSATION_ID   VARCHAR2(36)    NOT NULL,
    SENDER_TYPE       VARCHAR2(16)    NOT NULL,
    SENDER_ID         VARCHAR2(64)    NOT NULL,
    MESSAGE_TYPE      VARCHAR2(16)    DEFAULT 'TEXT'       NOT NULL,
    CONTENT           CLOB,
    CLIENT_MESSAGE_ID VARCHAR2(64)    NOT NULL,
    SEQ_NO            NUMBER(19)      NOT NULL,
    CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    DELIVERED_AT      TIMESTAMP,
    READ_AT           TIMESTAMP,
    CONSTRAINT PK_CHAT_MESSAGE      PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT FK_MSG_CONV          FOREIGN KEY (CONVERSATION_ID) REFERENCES CHAT_CONVERSATION(CONVERSATION_ID),
    CONSTRAINT UQ_CONV_CLIENT_MSG   UNIQUE (CONVERSATION_ID, CLIENT_MESSAGE_ID),
    CONSTRAINT UQ_CONV_SEQ          UNIQUE (CONVERSATION_ID, SEQ_NO)
);

CREATE INDEX IDX_MESSAGE_CONV_SEQ ON CHAT_MESSAGE (CONVERSATION_ID, SEQ_NO);

-- 3. CHAT_CONTEXT: Lưu context của conversation tại thời điểm chat
CREATE TABLE CHAT_CONTEXT (
    CONVERSATION_ID   VARCHAR2(36)    NOT NULL,
    SCREEN_NAME       VARCHAR2(128),
    FEATURE           VARCHAR2(128),
    LAST_ACTION       VARCHAR2(128),
    APP_VERSION       VARCHAR2(32),
    OS                VARCHAR2(32),
    DEVICE            VARCHAR2(128),
    CONTEXT_JSON      CLOB,
    CONSTRAINT PK_CHAT_CONTEXT PRIMARY KEY (CONVERSATION_ID)
);

-- 4. CHAT_ATTACHMENT: Chỉ lưu metadata của file
CREATE TABLE CHAT_ATTACHMENT (
    ATTACHMENT_ID     VARCHAR2(36)    NOT NULL,
    MESSAGE_ID        VARCHAR2(36)    NOT NULL,
    CONVERSATION_ID   VARCHAR2(36)    NOT NULL,
    FILE_NAME         VARCHAR2(255),
    FILE_TYPE         VARCHAR2(128),
    FILE_SIZE         NUMBER(19),
    OBJECT_KEY        VARCHAR2(512),
    CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHAT_ATTACHMENT PRIMARY KEY (ATTACHMENT_ID),
    CONSTRAINT FK_ATTACH_MSG  FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGE(MESSAGE_ID)
);

CREATE INDEX IDX_ATTACH_MSG ON CHAT_ATTACHMENT (MESSAGE_ID);

-- 5. CHAT_OUTBOX: Outbox pattern cho Kafka event publishing
CREATE TABLE CHAT_OUTBOX (
    EVENT_ID      VARCHAR2(36)    NOT NULL,
    AGGREGATE_ID  VARCHAR2(36)    NOT NULL,
    EVENT_TYPE    VARCHAR2(128)   NOT NULL,
    PAYLOAD       CLOB            NOT NULL,
    STATUS        VARCHAR2(16)    DEFAULT 'PENDING'     NOT NULL,
    CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP  NOT NULL,
    PUBLISHED_AT  TIMESTAMP,
    CONSTRAINT PK_CHAT_OUTBOX PRIMARY KEY (EVENT_ID)
);

CREATE INDEX IDX_OUTBOX_STATUS ON CHAT_OUTBOX (STATUS);

-- 6. CHAT_ASSIGNMENT_HISTORY: Lưu lịch sử Agent được assign/handover
CREATE TABLE CHAT_ASSIGNMENT_HISTORY (
    ID              VARCHAR2(36)    NOT NULL,
    CONVERSATION_ID VARCHAR2(36)    NOT NULL,
    FROM_AGENT      VARCHAR2(64),
    TO_AGENT        VARCHAR2(64),
    ASSIGN_TYPE     VARCHAR2(16),
    ASSIGNED_BY     VARCHAR2(64),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHAT_ASSIGN_HIST PRIMARY KEY (ID),
    CONSTRAINT FK_ASSIGN_CONV FOREIGN KEY (CONVERSATION_ID) REFERENCES CHAT_CONVERSATION(CONVERSATION_ID)
);

CREATE INDEX IDX_ASSIGN_CONV ON CHAT_ASSIGNMENT_HISTORY (CONVERSATION_ID);

-- 7. CHAT_AUDIT_LOG: Lưu audit trail
CREATE TABLE CHAT_AUDIT_LOG (
    ID              VARCHAR2(36)    NOT NULL,
    CONVERSATION_ID VARCHAR2(36)    NOT NULL,
    EVENT_TYPE      VARCHAR2(64)    NOT NULL,
    ACTOR_ID        VARCHAR2(64),
    ACTOR_TYPE      VARCHAR2(16),
    OLD_VALUE       CLOB,
    NEW_VALUE       CLOB,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHAT_AUDIT_LOG PRIMARY KEY (ID)
);

CREATE INDEX IDX_AUDIT_CONV ON CHAT_AUDIT_LOG (CONVERSATION_ID);