CREATE TABLE CHAT_RATING (
    RATING_ID VARCHAR2(50) NOT NULL,
    CONVERSATION_ID VARCHAR2(50) NOT NULL,
    RATING NUMBER(10,0) NOT NULL,
    COMMENT_TEXT CLOB,
    CREATED_AT TIMESTAMP (6) NOT NULL,
    PRIMARY KEY (RATING_ID)
);

ALTER TABLE CHAT_RATING ADD CONSTRAINT UNQ_RATING_CONVERSATION UNIQUE (CONVERSATION_ID);
CREATE INDEX IDX_RATING_CREATED ON CHAT_RATING (CREATED_AT);
